---
- name: install default jdk
  apt: 
    name: default-jdk
    update_cache: yes
    state: present

- name: add tomcat group
  group: 
    name: tomcat
    state: present

- name: add tomcat user
  user: 
    name: tomcat
    home: /opt/tomcat
    shell: /bin/false
    group: tomcat

- name: download tomcat tar file
  uri: 
    url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.87/bin/apache-tomcat-9.0.87.tar.gz
    dest: /tmp
    creates: /tmp/apache-tomcat-9.0.87.tar.gz

- name: create tomcat directory
  file: 
    path: /opt/tomcat
    state: directory

- name: untar files
  shell: "tar xzvf /tmp/apache-tomcat-9*tar.gz -C /opt/tomcat --strip-components=1"

- name: update group permissions
  file: 
    path: /opt/tomcat
    group: tomcat
    mode: g+w
    recurse: true

- name: update conf permissions
  file: 
    path: /opt/tomcat/conf
    mode: g+r
    recurse: true

- name: update conf exec permissions
  file:
    path: /opt/tomcat/conf
    mode: g+x

- name: change owner
  file: 
    path: "/opt/tomcat/{{ item }}"
    group: tomcat
    recurse: true
  loop: 
    - "webapps/"
    - "work/"
    - "temp/"
    - "logs/"

- name: copy tomcat service file
  copy: 
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service
  notify: 
    - Restart Daemon
    - Start Tomcat
