---
- name: install java
  apt: 
    name: openjdk-17-jdk
    update_cache: true
    state: present

- name: download jenkins key
  uri: 
    url: 'https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key'
    dest: '/usr/share/keyrings/jenkins-keyring.asc'
    creates: '/usr/share/keyrings/jenkins-keyring.asc'

- name: add keyrings to jenkins sources
  shell: |
    echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
    https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
    /etc/apt/sources.list.d/jenkins.list > /dev/null 

- name: install jenkins
  apt: 
    name: jenkins
    update_cache: true
    state: present
